package com.trodar.designtemplate.theme.color

import androidx.compose.ui.graphics.Color

val primaryLightHighContrast = Color(0xFF29313B)
val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
val primaryContainerLightHighContrast = Color(0xFF0091EE)
val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
val secondaryLightHighContrast = Color(0xFFDCA101)
val onSecondaryLightHighContrast = Color(0xFFD9D9D9)
val secondaryContainerLightHighContrast = Color(0xFFF7FDFF)
val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
val tertiaryLightHighContrast = Color(0xFF00281C)
val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightHighContrast = Color(0xFF004D39)
val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
val errorLightHighContrast = Color(0xFF4E0002)
val onErrorLightHighContrast = Color(0xFFFFFFFF)
val errorContainerLightHighContrast = Color(0xFF8C0009)
val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
val backgroundLightHighContrast = Color(0xFFF6FAFE)
val onBackgroundLightHighContrast = Color(0xFF181C20)
val surfaceLightHighContrast = Color(0xFFCADDFC)
val onSurfaceLightHighContrast = Color(0xFF000000)
val surfaceVariantLightHighContrast = Color(0xFFDDE3EA)
val onSurfaceVariantLightHighContrast = Color(0xFF1E252A)
val outlineLightHighContrast = Color(0xFF3D4449)
val outlineVariantLightHighContrast = Color(0xFF3D4449)
val scrimLightHighContrast = Color(0xFF000000)
val inverseSurfaceLightHighContrast = Color(0xFF2D3135)
val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
val inversePrimaryLightHighContrast = Color(0xFFDBEFFF)
val surfaceDimLightHighContrast = Color(0xFFD7DADF)
val surfaceBrightLightHighContrast = Color(0xFFF6FAFE)
val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightHighContrast = Color(0xFFF1F4F9)
val surfaceContainerLightHighContrast = Color(0xFFEBEEF3)
val surfaceContainerHighLightHighContrast = Color(0xFFE5E8ED)
val surfaceContainerHighestLightHighContrast = Color(0xFFDFE3E7)